name: Compiler

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: make
  
  valgrind:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: sudo apt-get install valgrind
    - run: make
    - run: chmod +x test/valgrind.sh
    - run: ./test/valgrind.sh
