name: Valgrind

# Only trigger when the build workflow succeeded
on:
  workflow_run:
    workflows: ["Compiler"]
    types:
      - completed

jobs:
  valgrind:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run valgrind test script
        run: ./test/valgrind.sh
